### ISSUE TITLE
wrong syntax in dataset

### ISSUE THREAD

**Issue by rajgoesout** [simon-weber/Programming-Language-Identification#1]
The syntax for block comments seems to be wrong in the python dataset.
https://github.com/simon-weber/Programming-Language-Identification/blob/master/database/python/blockComments.txt#L2

**Comment by simon-weber** [comment]
iirc the database dir is just a mapping of tokens to occurrence for the files that were trained on; it only means the tokens were in the input, not that they're a valid part of the language. Read the paper for the details.
